language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - dev

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test

#if: branch = master
#stages
#   provider: gae
#   keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
#   project: "xxxx-server"
# -name: deploy
# if: branch = master
